version: "3.9"
name: bingo_prado
services:
  bingo_p_nginx_default:
    container_name: bingo_p_nginx_default
    image: nginx:1.17.8
    ports:
      - 8060:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../web:/var/www
      # - ../error/error.default.log:/var/log/nginx/error.default.log
    links:
      - bingo_p_php_default
  bingo_p_php_default:
    container_name: bingo_p_php_default
    build: ./php
    working_dir: /var/www
    volumes:
      - ../web:/var/www
  bingo_p_php_mysql:
    container_name: bingo_p_php_mysql
    restart: always
    image: mariadb:10.6
    ports:
      - 8061:3306
    volumes:
      - ../database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Argentina/Buenos_Aires
